---
- name: Download cloud image for proxmox
  hosts: proxmox
  gather_facts: false

  tasks:
    - name: Download cloud image
      ansible.builtin.import_role:
        name: sysengquick.proxmox.cloud_image

- name: Create VM on proxmox host
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create VM
      ansible.builtin.import_role:
        name: sysengquick.proxmox.create_vm
