---
- name: Gather facts
  ansible.builtin.setup:
    gather_subset:
      - "!all"
      - "!min"
      - os_family
  when: "'os_family' is not in ansible_facts"

- name: Root Tasks Block
  become: true
  block:
    - name: Update package cache
      ansible.builtin.include_tasks:
        file: "{{ ansible_facts.os_family }}.yml"
      when: ansible_facts.os_family is in supported_families
      vars:
        supported_families:
          - Archlinux
          - Debian
          - RedHat
