---
- name: Create non-root user for ansible
  hosts: "{{ targets | default('lxc') }}"
  gather_facts: false

  tasks:
    - name: Install sudo
      ansible.builtin.import_role:
        name: sysengquick.tutorial.package
      vars:
        package_name: sudo

    - name: Create ansible user
      ansible.builtin.import_role:
        name: sysengquick.tutorial.user
      vars:
        user_name: ansible
        user_sudo: true
