---
ansible:
  children:
    lxc:
      children:
        servers:
          hosts:
            ath-arch.local.technoplaza.net:
            ath-bookworm.local.technoplaza.net:
            ath-centos8.local.technoplaza.net:
            ath-jammy.local.technoplaza.net:
            ath-rocky9.local.technoplaza.net:
          vars:
            ansible_ssh_common_args: "-o ProxyCommand=\
              'ssh -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              -W %h:%p ansible@ath-proxy.local.technoplaza.net'"
    pve:
      children:
        proxy:
          hosts:
            ath-proxy.local.technoplaza.net:
  vars:
    ansible_user: ansible
