---
- name: Gather facts
  ansible.builtin.setup:
    gather_subset:
      - "!all"
      - "!min"
      - os_family

- name: Install neofetch
  ansible.builtin.include_tasks:
    file: "install-{{ ansible_facts.os_family }}.yml"
