---
- name: Register values
  ansible.builtin.set_fact:
    create_vm_values_combined: |
      {{
        create_vm_values_defaults
        | ansible.builtin.combine(create_vm_values, recursive=true)
      }}

- name: Create cloud VM
  community.general.proxmox_kvm:
    api_host: "{{ create_vm_api['host'] }}"
    api_user: "{{ create_vm_api['user'] }}"
    api_token_id: "{{ create_vm_api['token_id'] }}"
    api_token_secret: "{{ create_vm_api['token_secret'] }}"
    name: "{{ values['name'] }}"
    agent: enabled=1
    balloon: "{{ values['balloon'] }}"
    boot: order=scsi0
    cipassword: "{{ values['cloud_init']['password'] }}"
    ciuser: "{{ values['cloud_init']['user'] }}"
    cores: "{{ values['cpu_cores'] }}"
    cpu: "{{ values['cpu_type'] }}"
    ide:
      ide2: "{{ values['cloud_init']['storage'] }}:cloudinit,\
        format={{ values['cloud_init']['format'] }}"
    ipconfig:
      ipconfig0: "{{ values['network']['ipconfig'] }}"
    memory: "{{ values['memory'] }}"
    net:
      net0: "model={{ values['network']['model'] }},\
        bridge={{ values['network']['bridge'] }},\
        firewall={{ values['network']['firewall'] }},\
        mtu={{ values['network']['mtu'] }}"
    node: "{{ values['node'] }}"
    onboot: "{{ values['onboot'] }}"
    ostype: l26
    scsi:
      scsi0: "{{ values['disk']['storage'] }}:0,\
        import-from={{ values['disk']['image']['storage'] }}\
        :{{ values['disk']['image']['vmid'] }}\
        /{{ image['filename'] }},\
        format={{ values['disk']['format'] }},\
        iothread={{ values['disk']['iothread'] }},\
        discard={{ values['disk']['discard'] }},\
        ssd={{ values['disk']['ssd'] }}"
    scsihw: virtio-scsi-single
    serial:
      serial0: socket
    sshkeys: "{{ values['cloud_init']['sshkeys'] }}"
    vga: serial0
  register: result
  vars:
    image: "{{ lookup('sysengquick.proxmox.cloud_image', values['disk']['image']['name']) }}"
    values: "{{ create_vm_values_combined }}"

- name: Save vmid
  ansible.builtin.set_fact:
    proxmox_vmid: "{{ result['vmid'] }}"

- name: Resize disk
  community.general.proxmox_disk:
    api_host: "{{ create_vm_api['host'] }}"
    api_user: "{{ create_vm_api['user'] }}"
    api_token_id: "{{ create_vm_api['token_id'] }}"
    api_token_secret: "{{ create_vm_api['token_secret'] }}"
    disk: scsi0
    vmid: "{{ proxmox_vmid }}"
    size: "{{ values['disk']['size'] }}G"
    state: resized
  vars:
    values: "{{ create_vm_values_combined }}"
