---
create_vm_api_defaults:
  validate_certs: true
create_vm_values_defaults:
  balloon: 0
  cloud_init:
    format: qcow2
    password: "$ecretPassw0rd!"
    sshkeys: ~
    storage: local
    user: ansible
  cpu_cores: 1
  cpu_type: host
  disk:
    discard: "on"
    format: qcow2
    image:
      name: "{{ global_cloud_image_name | default('ubuntu') }}"
      storage: local
      vmid: 0
    iothread: 1
    size: 8
    ssd: 1
    storage: local
  memory: 2048
  network: []
  onboot: false
