---
- name: Create image directory
  ansible.builtin.file:
    state: directory
    path: "{{ cloud_image_dest }}"
    mode: "0700"
  become: true

- name: Delete temp file at the end of the block
  vars:
    image: "{{ lookup('sysengquick.proxmox.cloud_image', cloud_image_name) }}"
  block:
    - name: Create tempfile
      ansible.builtin.tempfile:
      register: tempfile

    - name: Download checksum
      ansible.builtin.get_url:
        dest: "{{ tempfile.path }}"
        mode: "0644"
        url: "{{ image['checksum_url'] }}"
      delegate_to: localhost
      run_once: true

    - name: Download cloud image
      ansible.builtin.get_url:
        dest: "{{ cloud_image_dest }}/{{ image['filename'] }}"
        mode: "0644"
        url: "{{ image['image_url'] }}"
        checksum: "{{ checksum }}"
      become: true
      vars:
        checksum: |-
          {{
            lookup('ansible.builtin.file', tempfile.path)
            | ansible.builtin.regex_search(regex)
            | ansible.builtin.regex_replace(regex, replace)
          }}
        regex: |-
          SHA(256|512) \({{ image['filename'] }}\) = ([a-f0-9]+)
        replace: |-
          sha\1:\2
  always:
    - name: Delete tempfile
      ansible.builtin.file:
        state: absent
        path: "{{ tempfile.path }}"
