---
argument_specs:
  main:
    short_description: &desc Downloads qcow2 cloud image to proxmox server
    description: *desc
    author:
      - John Ratliff <john@technoplaza.net>
    options:
      cloud_image_name:
        type: str
        choices:
          - alma
          - alma-8
          - alma-9
          - centos
          - centos-8
          - centos-9
          - debian
          - debian-12
          - debian-bookworm
          - fedora
          - fedora-40
          - rocky
          - rocky-8
          - rocky-9
          - ubuntu
          - ubuntu-22.04
          - ubuntu-24.04
          - ubuntu-jammy
          - ubuntu-noble
          - ubuntu-minimal
          - ubuntu-minimal-jammy
          - ubuntu-minimal-noble
        default: ubuntu
        description: Cloud image name to download
        required: false
      cloud_image_api_proxmox:
        type: dict
        required: true
        description: The proxmox API settings
        options:
          host:
            type: str
            required: true
            description: The proxmox API host
          user:
            type: str
            required: true
            description: The user associated with the API token
          token_id:
            type: str
            required: true
            description: The token ID
          token_secret:
            type: str
            required: true
            description: The API token
          validate_certs:
            type: bool
            default: true
            description: True to validate the proxmox API cert; false to bypass validation (useful for self-signed certs)
            required: false
      cloud_image_storage_id:
        type: str
        default: local
        description: The proxmox storage pool ID to place the image
        required: false
