---
argument_specs:
  main:
    short_description: &desc Downloads qcow2 cloud image to proxmox server
    description: *desc
    author:
      - John Ratliff <john@technoplaza.net>
    options:
      cloud_image_dest:
        type: str
        default: /var/lib/vz/images/0
        description: Path to store the cloud image files
        required: false
      cloud_image_name:
        type: str
        choices:
          - fedora
          - fedora-40
          - rocky
          - rocky-9.4
          - ubuntu
          - ubuntu-24.04
          - ubuntu-noble
        default: ubuntu
        description: Cloud image name to download
        required: false
