---
argument_specs:
  main:
    short_description: &desc Downloads qcow2 cloud image to proxmox server
    description: *desc
    author:
      - John Ratliff <john@technoplaza.net>
    options:
      cloud_image_dest:
        type: str
        default: /var/lib/vz/images/0
        description: Path to store the cloud image files
        required: false
      cloud_image_name:
        type: str
        choices:
          - alma
          - alma-8
          - alma-9
          - centos
          - centos-8
          - centos-9
          - debian
          - debian-12
          - fedora
          - fedora-40
          - rocky
          - rocky-8
          - rocky-9
          - ubuntu
          - ubuntu-22.04
          - ubuntu-24.04
          - ubuntu-jammy
          - ubuntu-noble
          - ubuntu-minimal
          - ubuntu-minimal-jammy
          - ubuntu-minimal-noble
        default: ubuntu
        description: Cloud image name to download
        required: false
