---
- name: Lookup home directory
  ansible.builtin.user:
    name: "{{ ansible_ssh_user }}"
    state: present
  check_mode: true
  register: user_info

- name: Write gitconfig
  ansible.builtin.template:
    src: gitconfig.j2
    dest: "{{ user_info['home'] }}/.gitconfig"
    mode: "0644"
