---
- name: Lookup user home directory
  ansible.builtin.setup:
    gather_subset:
      - "!all"
      - "!min"
      - user_dir
  when: "'user_dir' is not in ansible_facts"

- name: Write gitconfig
  ansible.builtin.template:
    src: gitconfig.j2
    dest: "{{ ansible_facts['user_dir'] }}/.gitconfig"
    mode: "0644"
  vars:
    values: |
      {{
        gitconfig_values_defaults
        | ansible.builtin.combine(gitconfig_values, recursive=true)
      }}
